runtime: nodejs
env: flex
skip_files:
- node_modules
resources:
  cpu: 1
  memory_gb: 0.5
automatic_scaling:
  min_num_instances: 1
  max_num_instances: 1
  cpu_utilization:
    target_utilization: 0.9
